import datetime
from decimal import Decimal

# Helper function to safely convert to Decimal
def to_decimal(value):
    if value is None:
        return Decimal('0.00')
    return Decimal(str(value))

# Define rewards configuration
REWARDS_CONFIG = {
    "points_per_paystub": 100,
    "points_per_referral": 500,
    "milestones": [
        {"name": "First Paystub", "points": 250, "achievement": "Paystub Pioneer"},
        {"name": "10 Paystubs", "points": 1000, "achievement": "Payroll Pro"},
        {"name": "50 Paystubs", "points": 5000, "achievement": "Master of the Ledger"},
    ],
    "tiers": [
        {"name": "Bronze", "min_points": 0, "multiplier": 1.0},
        {"name": "Silver", "min_points": 2000, "multiplier": 1.1},
        {"name": "Gold", "min_points": 5000, "multiplier": 1.25},
        {"name": "Platinum", "min_points": 10000, "multiplier": 1.5},
    ]
}

def calculate_points_for_paystub(paystub_count):
    """
    Calculates the base points for generating a paystub, applying tier multiplier.
    
    :param paystub_count: The total number of paystubs generated by the user.
    :return: The points to be awarded for the current paystub.
    """
    # Simple logic: base points for the paystub itself
    base_points = REWARDS_CONFIG["points_per_paystub"]
    
    # Check for milestone achievement (only on the first time)
    milestone_points = 0
    for milestone in REWARDS_CONFIG["milestones"]:
        if paystub_count == milestone["name"].split()[0] and paystub_count > 0:
            milestone_points += milestone["points"]
            
    return base_points + milestone_points

def get_current_tier(total_points):
    """
    Determines the user's current reward tier based on total points.
    
    :param total_points: The user's total accumulated points.
    :return: The current tier name and multiplier.
    """
    current_tier = REWARDS_CONFIG["tiers"][0] # Default to Bronze
    for tier in REWARDS_CONFIG["tiers"]:
        if total_points >= tier["min_points"]:
            current_tier = tier
        else:
            break # Tiers are sorted by min_points
            
    return current_tier

def update_user_rewards(user, new_points_earned):
    """
    Updates the user's total points and checks for new tier progression.
    
    :param user: The User object (assumed to have 'total_points' and 'reward_tier' attributes).
    :param new_points_earned: The points earned in the current transaction.
    :return: A dictionary with the new total points, new tier, and any new achievements.
    """
    # Use Decimal for precision
    current_points = to_decimal(user.total_points)
    
    # Apply tier multiplier to new points (e.g., Gold tier earns 1.25x points)
    current_tier = get_current_tier(current_points)
    multiplier = current_tier["multiplier"]
    
    multiplied_points = to_decimal(new_points_earned) * Decimal(str(multiplier))
    new_total_points = current_points + multiplied_points
    
    # Check for new tier
    new_tier = get_current_tier(new_total_points)
    tier_upgraded = new_tier["name"] != current_tier["name"]
    
    # Check for milestones (assuming user.paystub_count has been incremented)
    new_achievements = []
    # This part would require access to the user's history of achievements to prevent re-awarding.
    # For simplicity, we'll assume the caller handles the paystub count update.
    
    # Update user object (simulated)
    # user.total_points = new_total_points
    # user.reward_tier = new_tier["name"]
    
    return {
        "new_total_points": new_total_points,
        "tier_upgraded": tier_upgraded,
        "new_tier": new_tier["name"],
        "points_multiplier": multiplier,
        "points_awarded": multiplied_points.quantize(Decimal('0.00')),
        "new_achievements": new_achievements # Placeholder for actual achievement logic
    }

if __name__ == '__main__':
    from collections import namedtuple
    
    # Mock User object
    MockUser = namedtuple('MockUser', ['total_points', 'reward_tier', 'paystub_count'])
    
    # Test 1: First Paystub (Paystub Count 1)
    user1 = MockUser(total_points=Decimal('0.00'), reward_tier='Bronze', paystub_count=0)
    paystub_count1 = 1
    points_for_paystub1 = REWARDS_CONFIG["points_per_paystub"]
    
    # Manually check for the first milestone
    milestone_points = 0
    if paystub_count1 == 1:
        milestone_points = REWARDS_CONFIG["milestones"][0]["points"]
        
    total_earned1 = points_for_paystub1 + milestone_points
    
    print("--- Test 1: First Paystub ---")
    rewards1 = update_user_rewards(user1, total_earned1)
    print(f"Points Earned: {total_earned1}")
    print(f"New Total Points: {rewards1['new_total_points']:.2f} (Expected: {total_earned1:.2f})")
    print(f"New Tier: {rewards1['new_tier']} (Expected: Bronze)")
    
    # Test 2: Tier Upgrade (Simulate user at 4900 points, generating 100 points)
    user2 = MockUser(total_points=Decimal('4900.00'), reward_tier='Gold', paystub_count=49)
    paystub_count2 = 50
    points_for_paystub2 = REWARDS_CONFIG["points_per_paystub"]
    
    # Manually check for the 50th milestone
    milestone_points2 = 0
    if paystub_count2 == 50:
        milestone_points2 = REWARDS_CONFIG["milestones"][2]["points"]
        
    total_earned2 = points_for_paystub2 + milestone_points2
    
    print("\n--- Test 2: Tier Upgrade to Gold (50th Paystub) ---")
    rewards2 = update_user_rewards(user2, total_earned2)
    print(f"Points Earned (Base + Milestone): {total_earned2}")
    print(f"Points Multiplier (Gold Tier): {rewards2['points_multiplier']:.2f}")
    print(f"Points Awarded (Multiplied): {rewards2['points_awarded']:.2f} (Expected: {(total_earned2 * Decimal('1.25')):.2f})")
    print(f"New Total Points: {rewards2['new_total_points']:.2f} (Expected: {Decimal('4900.00') + (total_earned2 * Decimal('1.25')):.2f})")
    print(f"New Tier: {rewards2['new_tier']} (Expected: Platinum - 4900 + 6375 = 11275)")
